### ISSUE TITLE
最近没有更新么？

### ISSUE THREAD

**Issue by enlangs** [baidu-lamp/baidu-hhvm#2]
新版本都到3.6.1了，你们没有更新么？

**Comment by huzhiguang** [comment]
内部有编译好的demo，但是没有release版本，目前公司使用的release版本是以3.0.1为基础，还有一些2.2

**Comment by enlangs** [comment]
那有没有 3.3的版本呢？

我的项目想尝试下HHVM，但是有很大部分代码是5.3+的。。。3.0.1 貌似不支持。

**Comment by huzhiguang** [comment]
��ã�3.0.1�汾֧��5.4�����﷨
________________________________________
������: shouyong [notifications@github.com]
����ʱ��: 2015��3��26�� 22:39
�ռ���: baidu-lamp/baidu-hhvm
����: Hu,Zhiguang
����: Re: [baidu-hhvm] ���û�и���ô�� (#2)

����û�� 3.3�İ汾�أ�

�ҵ���Ŀ�볢����HHVM�������кܴ󲿷ִ�����5.3+�ġ�����3.0.1 ò�Ʋ�֧�֡�

��

**Comment by enlangs** [comment]
伙计，你的回复是乱码。。。

你的意思是 3.0.1支持PHP 5.4+特性 ？

**Comment by huzhiguang** [comment]
3.0.1已经支持PHP 5.4以上的特性了，2.2都是支持5.4以上语法了

**Comment by enlangs** [comment]
好的，非常感谢。
